VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
ENCODER_MAP_ENABLE = yes
VIALRGB_ENABLE = yes
RGB_MATRIX_ENABLE = yes
QMK_SETTINGS = yes

LTO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
