#pragma once

#include_next <mcuconf.h>

#undef STM32_PWM_USE_TIM15
#define STM32_PWM_USE_TIM15 TRUE

#undef STM32_PWM_TIM15_IRQ_PRIORITY
#define STM32_PWM_TIM15_IRQ_PRIORITY 2

#define STM32_TIM15_SUPPRESS_ISR
